name: CI

on: [push]

jobs:
  sast_scan:
    name: Running Bandit Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # by specifying the version, we can avoid the need to run `python -m pip install --upgrade pip` to upgrade pip

      # Install Bandit
      - name: Install Bandit
        run: pip install bandit

      # Run Bandit Scan
      - name: Run Bandit Scan
        run: bandit -ll -ii -r -f json -o bandit-report.json .

      # Upload Bandit Report
      - name: Upload Bandit Report
        uses: actions/upload-artifact@v2
        if: always() # always upload the report, even if the previous steps failed
        with:
          name: bandit-report
          path: bandit-report.json
